<?php
	
	 //ja  dasboard
    $language_jp['We Are Comming Soon'] = '私たちはすぐに来ています';
    $language_jp['PLEASE GIVE US A MOMENT TO SORT THINGS OUT'] = '物事を整理する瞬間を教えてください';
    $language_jp['Dashboard'] = 'ダッシュボード';
    $language_jp['Swap'] = 'スワップ';
    $language_jp['Downlines'] = 'ダウンライン';
    $language_jp['Uplines'] = 'アップライン';
    $language_jp['Lost Profits'] = '失われた利益';
    $language_jp['Promo'] = 'プロモ';
    $language_jp['Exit'] = '出口';
    $language_jp['Total Earned'] = '総ドル';
	$language_jp['Total BTC'] = '合計ビットコイン';
    $language_jp['Level Profits'] = '合計イーサリアム';
    $language_jp['Uni Level'] = 'パートナー';
    $language_jp['Pools Profits'] = 'レベル利益';
    $language_jp['Global Dividend'] = 'グローバル配当';
    $language_jp['Available Fund'] = '利用可能な資金';
    $language_jp['The growth of structure'] = 'ネットワークの成長';
    $language_jp['Your Referral Link'] = 'あなたの紹介リンク';
    $language_jp['Link for redirect to the Trust Wallet Dapp Browser'] = 'Trust Wallet Dapp Browserにリダイレクトするためのリンク';
    $language_jp['Your Downline Partners'] = 'あなたのダウンラインパートナー';
    $language_jp['Commission Received'] = '受け取った手数料';
    $language_jp['LEVEL'] = 'レベル';
    $language_jp['Inactive'] = '非活性';
    $language_jp['Active'] = 'アクティブ';
    $language_jp['Purchases'] = '購入';
    $language_jp['Buy'] = '購入';
    $language_jp['Days'] = '日々';
    $language_jp['Contract Address'] = '契約住所';
    $language_jp['Address'] = '住所';
    $language_jp['project month'] = 'プロジェクト月間';
    $language_jp['total participants'] = '総参加者';
    $language_jp['total transactions'] = '合計トランザクション';
    $language_jp['total'] = '合計';
    $language_jp['equivalent to'] = 'に相当';
    $language_jp['USER ID'] = 'ユーザーID';
    $language_jp['Auto Pool'] = '自動プール';
    $language_jp['Promotions'] = 'プロモーション';
    $language_jp['Wallet Address'] = 'ウォレットアドレス';
    $language_jp['Date Joined'] = '入社日';
    $language_jp['Date'] = '日付';
    $language_jp['From whom'] = '誰から';
    $language_jp['Received'] = '受け取りました';
    $language_jp['Presentation'] = 'プレゼンテーション';
    $language_jp['Articles'] = '記事';
    $language_jp['Banner'] = 'バナー';
    $language_jp['Video'] = 'ビデオ';
    $language_jp['Amount'] = '量';
    $language_jp['Line'] = 'ライン';
    $language_jp['Copy'] = 'コピーする';


//login
	$language_jp['by'] = '沿って';
	$language_jp['All RIGHT RESERVED'] = 'すべての権利予約';
	$language_jp['Chat in Telegram'] = '電報でチャット';
	$language_jp['Login Manually'] = '手動でログイン';
	$language_jp['Any question you can get in our chat:'] = 'あなたが私たちのチャットで得ることができる質問：';
	$language_jp['Follow us on social networks'] = 'ソーシャルネットワークでフォローする';
	$language_jp['Login']='ログインする';
	$language_jp['smart-contract:']='スマート契約：';
	$language_jp['Enter User ID or Ether Address'] = 'ユーザーIDまたはEtherアドレスを入力してください';
	$language_jp['Or you can enter manually, Your ether address or User ID'] = 'または、手動で入力することもできます。イーサアドレスまたはユーザーID';
	$language_jp['Login Automatically'] = '自動的にログイン';
	$language_jp['Automatic login if you have one of the following wallets:'] = '次のウォレットのいずれかを持っている場合の自動ログイン：';
	
	
    //german  dasboard
    $language_de['We Are Comming Soon'] = 'Wir kommen bald';
    $language_de['PLEASE GIVE US A MOMENT TO SORT THINGS OUT'] = 'BITTE GEBEN SIE UNS EINEN MOMENT, UM DINGE ZU SORTIEREN';
    $language_de['Dashboard'] = 'Instrumententafel';
    $language_de['Swap'] = 'Tauschen';
    $language_de['Downlines'] = 'Downlines';
    $language_de['Uplines'] = 'Uplines';
    $language_de['Lost Profits'] = 'Verlorene Gewinne';
    $language_de['Promo'] = 'Promo';
    $language_de['Exit'] = 'Ausgang';
    $language_de['Total Earned'] = 'Gesamtdollar';
	$language_de['Total BTC'] = 'Bitcoins insgesamt';
    $language_de['Level Profits'] = 'Total Ethereum';
    $language_de['Uni Level'] = 'Partners';
    $language_de['Pools Profits'] = 'Level Gewinne';
    $language_de['Global Dividend'] = 'Globale Dividende';
    $language_de['Available Fund'] = 'Verfügbarer Fonds';
    $language_de['The growth of structure'] = 'Das Wachstum des Netzwerks';
    $language_de['Your Referral Link'] = 'Ihr Empfehlungslink';
    $language_de['Link for redirect to the Trust Wallet Dapp Browser'] = 'Link zur Weiterleitung zum Trust Wallet Dapp Browser';
    $language_de['Your Downline Partners'] = 'Ihre Downline-Partner';
    $language_de['Commission Received'] = 'Provision erhalten';
    $language_de['LEVEL'] = 'NIVEAU';
    $language_de['Inactive'] = 'Inaktiv';
    $language_de['Active'] = 'Aktiv';
    $language_de['Purchases'] = 'Einkäufe';
    $language_de['Buy'] = 'KAUFEN';
    $language_de['Days'] = 'Tage';
    $language_de['Contract Address'] = 'Vertragsadresse';
    $language_de['Address'] = 'Adresse';
    $language_de['project month'] = 'PROJEKTMONAT';
    $language_de['total participants'] = 'GESAMT TEILNEHMER';
    $language_de['total transactions'] = 'Gesamttransaktionen';
    $language_de['total'] = 'gesamt';
    $language_de['equivalent to'] = 'gleichwertig';
    $language_de['USER ID'] = 'BENUTZERIDENTIFIKATION';
    $language_de['Auto Pool'] = 'Auto Pool';
    $language_de['Promotions'] = 'Promotions';
    $language_de['Wallet Address'] = 'Brieftaschenadresse';
    $language_de['Date Joined'] = 'Beitrittsdatum';
    $language_de['Date'] = 'Datum';
    $language_de['From whom'] = 'From whom';
    $language_de['Received'] = 'Empfangen';
    $language_de['Presentation'] = 'Präsentation';
    $language_de['Articles'] = 'Artikel';
    $language_de['Banner'] = 'Banner';
    $language_de['Video'] = 'Video';
    $language_de['Amount'] = 'Menge';
    $language_de['Line'] = 'Linie';
    $language_de['Copy'] = 'Kopieren';


//login
	$language_de['by'] = 'durch';
	$language_de['All RIGHT RESERVED'] = 'Alle Rechte vorbehalten';
	$language_de['Chat in Telegram'] = 'Chatten Sie im Telegramm';
	$language_de['Any question you can get in our chat:'] = 'Jede Frage, die Sie in unserem Chat bekommen können:';
	$language_de['Follow us on social networks'] = 'Follow us on social networks';
	$language_de['Login Manually'] = 'Manuell anmelden';
	$language_de['Login']='Anmeldung';
	$language_de['smart-contract:']='Smart-Vertrag:';
	$language_de['Enter User ID or Ether Address'] = 'Geben Sie die Benutzer-ID oder die Ether-Adresse ein';
	$language_de['Or you can enter manually, Your ether address or User ID'] = 'Or you can enter manually, Your ether address or User ID';
	$language_de['Login Automatically'] = 'Automatisch anmelden';
	$language_de['Automatic login if you have one of the following wallets:'] = 'Automatische Anmeldung, wenn Sie über eine der folgenden Brieftaschen verfügen:';
	
	
	//hindi dasboard
	$language_in['We Are Comming Soon'] = 'वी आर कमिंग सून';
    $language_in['PLEASE GIVE US A MOMENT TO SORT THINGS OUT'] = 'कृपया बाहर भेजने के लिए एक दिन का उपयोग करें';
    $language_inlanguage_hi['Dashboard'] = 'डैशबोर्ड';
    $language_in['Swap'] = 'विनिमय';
    $language_in['Dashboard'] = 'डैशबोर्ड';
    $language_in['Downlines'] = 'निचली पंक्ति';
    $language_in['Uplines'] = 'अपलाइन';
    $language_in['Lost Profits'] = 'खोया हुआ लाभ';
    $language_in['Promo'] = 'प्रोमो';
    $language_in['Exit'] = 'बाहर जाएं';
    $language_in['Total Earned'] = 'कुल कमाई';
	$language_in['Total BTC'] = 'कुल बिटकॉइन';
    $language_in['Level Profits'] = 'कुल जातीय';
    $language_in['Uni Level'] = 'भागीदारों';
    $language_in['Pools Profits'] = 'स्तर लाभ';
    $language_in['Global Dividend'] = 'ग्लोबल डिविडेंड';
    $language_in['Available Fund'] = 'उपलब्ध फंड';
    $language_in['The growth of structure'] = 'नेटवर्क का विकास';
    $language_in['Your Referral Link'] = 'आपका संदर्भ लिंक';
    $language_in['Link for redirect to the Trust Wallet Dapp Browser'] = 'ट्रस्ट वॉलेट डैप ब्राउज़र पर पुनर्निर्देशित करने के लिए लिंक';
    $language_in['Your Downline Partners'] = 'आपका डाउनलाइन पार्टनर्स';
    $language_in['Commission Received'] = 'कमीशन प्राप्त किया';
    $language_in['LEVEL'] = 'स्तर';
    $language_in['Inactive'] = 'निष्क्रिय';
    $language_in['Active'] = 'सक्रिय';
    $language_in['Purchases'] = 'खरीद';
    $language_in['Buy'] = 'खरीदें';
    $language_in['Days'] = 'दिन';
    $language_in['Contract Address'] = 'अनुबंध का पता';
    $language_in['Address'] = 'पता';
    $language_in['project month'] = 'परियोजना महीने';
    $language_in['total participants'] = 'कुल भाग';
    $language_in['total transactions'] = 'कुल लेनदेन';
    $language_in['total'] = 'संपूर्ण';
    $language_in['equivalent to'] = 'के बराबर';
    $language_in['USER ID'] = 'यूज़र आईडी';
    $language_in['Auto Pool'] = 'ऑटो पूल';
    $language_in['Promotions'] = 'प्रचार';
    $language_in['Wallet Address'] = 'बटुआ का पता';
    $language_in['Date Joined'] = 'शामिल होने का दिनांक';
    $language_in['Date'] = 'तारीख';
    $language_in['From whom'] = 'किस से';
    $language_in['Received'] = 'प्राप्त किया';
    $language_in['Presentation'] = 'प्रस्तुतीकरण';
    $language_in['Articles'] = 'सामग्री';
    $language_in['Banner'] = 'बैनर';
    $language_in['Video'] = 'वीडियो';
    $language_in['Amount'] = 'रकम';
    $language_in['Line'] = 'लाइन';
    $language_in['Copy'] = 'प्रतिलिपि';


//login
	$language_in['by'] = 'द्वारा';
	$language_in['All RIGHT RESERVED'] = 'सर्वाधिकार सुरक्षितED';
	$language_in['Chat in Telegram'] = 'टेलीग्राम में चैट करें';
	$language_in['Any question you can get in our chat:'] = 'कोई भी प्रश्न आप हमारी चैट में प्राप्त कर सकते हैं:';
	$language_in['Follow us on social networks'] = 'सामाजिक नेटवर्कों पर हमारा अनुसरण करें';
	$language_in['Login Manually'] = 'मैन्युअल रूप से लॉगिन करें';
	$language_in['Login']='लॉग इन करें';
	$language_in['smart-contract:']='स्मार्ट-अनुबंध:';
	$language_in['Enter User ID or Ether Address'] = 'उपयोगकर्ता आईडी या ईथर पता दर्ज करें';
	$language_in['Or you can enter manually, Your ether address or User ID'] = 'या आप मैन्युअल रूप से, आपका ईथर पता या उपयोगकर्ता आईडी दर्ज कर सकते हैं';
	$language_in['Login Automatically'] = 'स्वचालित रूप से लॉगिन करें';
	$language_in['Automatic login if you have one of the following wallets:'] = 'यदि आपके पास निम्नलिखित वॉलेट में से एक है, तो स्वचालित लॉगिन';


    //RUSSIAN dasboard
    $language_ru['We Are Comming Soon'] = 'Мы скоро приедем';
    $language_ru['PLEASE GIVE US A MOMENT TO SORT THINGS OUT'] = 'ПОЖАЛУЙСТА, ДАЙТЕ НАМ МОМЕНТ, ЧТОБЫ РАССМОТРЕТЬ';
    $language_ru['Dashboard'] = 'Приборная доска';
    $language_ru['Swap'] = 'обмен';
    $language_ru['Downlines'] = 'партнеры';
    $language_ru['Uplines'] = 'Аплайны';
    $language_ru['Lost Profits'] = 'Потерянная прибыль';
    $language_ru['Promo'] = 'рекламный';
    $language_ru['Exit'] = 'Выход';
    $language_ru['Total Earned'] = 'Всего заработано';
	$language_ru['Total BTC'] = 'Всего биткойнов';
    $language_ru['Level Profits'] = 'Уровень Прибыль';
    $language_ru['Uni Level'] = 'партнеры';
    $language_ru['Pools Profits'] = 'Прибыль Бассейны';
    $language_ru['Global Dividend'] = 'Глобальный Дивиденд';
    $language_ru['Available Fund'] = 'Доступный фонд';
    $language_ru['The growth of structure'] = 'Рост структуры';
    $language_ru['Your Referral Link'] = 'Ваша реферальная ссылка';
    $language_ru['Link for redirect to the Trust Wallet Dapp Browser'] = 'Подробности о вашем партнере';
    $language_ru['Your Downline Partners'] = 'Ваши партнеры по сети';
    $language_ru['Commission Received'] = 'Комиссия получена';
    $language_ru['LEVEL'] = 'УРОВЕНЬ';
    $language_ru['Inactive'] = 'Неактивный';
    $language_ru['Active'] = 'активный';
    $language_ru['Purchases'] = 'Покупки';
	$language_ru['Buy'] = 'купить';
	$language_ru['Days'] = 'дней';
	$language_ru['Contract Address'] = 'Адрес контракта';
	$language_ru['Address'] = 'контракта';
	$language_ru['project month'] = 'МЕСЯЦ ПРОЕКТА';
	$language_ru['total participants'] = 'ВСЕГО УЧАСТНИКОВ';
	$language_ru['total transactions'] = 'Всего транзакций';
	$language_ru['total'] = 'ВСЕГО';
	$language_ru['equivalent to'] = 'эквивалентно';
	$language_ru['USER ID'] = 'ID ПОЛЬЗОВАТЕЛЯ';
	$language_ru['Auto Pool'] = 'Авто бассейн';
	$language_ru['Promotions'] = 'Акции';
	$language_ru['Wallet Address'] = 'Адрес кошелька';
	$language_ru['Date Joined'] = 'Дата регистрации';
	$language_ru['Date'] = 'Дата';
	$language_ru['From whom'] = 'От кого';
	$language_ru['Received'] = 'Получил';
	$language_ru['Presentation'] = 'презентация';
	$language_ru['Articles'] = 'статьи';
	 $language_ru['Banner'] = 'Баннер';
    $language_ru['Video'] = 'видео';
    $language_ru['Amount'] = 'Количество';
    $language_ru['Line'] = 'Линия';
    $language_ru['Copy'] = 'копия';

	//login
	$language_ru['by'] = 'по';
	$language_ru['All RIGHT RESERVED'] = 'Все права защищены';
	$language_ru['Chat in Telegram'] = 'Чат в Telegram';
	$language_ru['Any question you can get in our chat:'] = 'Любой вопрос вы можете получить в нашем чате:';
	$language_ru['Follow us on social networks'] = 'Следите за нами в социальных сетях';
	$language_ru['Login Manually'] = 'Войти вручную';
    $language_ru['Login']='Войти';
	$language_ru['smart-contract:']='смарт-контракт:';
	$language_ru['Enter User ID or Ether Address'] = 'Введите идентификатор пользователя или адрес эфира';
	$language_ru['Or you can enter manually, Your ether address or User ID'] = 'Или вы можете ввести вручную, ваш эфирный адрес или идентификатор пользователя';
	$language_ru['Login Automatically'] = 'Войти автоматически';
	$language_ru['Automatic login if you have one of the following wallets:'] = 'Автоматический вход, если у вас есть один из следующих кошельков:';
	
	
    
     
    //ENGLISH dasboard
    $language_en['We Are Comming Soon'] = 'We Are Coming Soon';
    $language_en['PLEASE GIVE US A MOMENT TO SORT THINGS OUT'] = 'PLEASE GIVE US A MOMENT TO SORT THINGS OUT';
    $language_en['Dashboard'] = 'Dashboard';
    $language_en['Swap'] = 'Swap';
    $language_en['Downlines'] = 'Downlines';
    $language_en['Uplines'] = 'Uplines';
    $language_en['Lost Profits'] = 'Lost Profits';
    $language_en['Promo'] = 'Promo';
    $language_en['Exit'] = 'Exit';
    $language_en['Total Earned'] = 'Total Dollars';
	$language_en['Total BTC'] = 'Total Bitcoins';
    $language_en['Level Profits'] = 'Total Ethereum';
    $language_en['Uni Level'] = 'Partners';
    $language_en['Pools Profits'] = 'Level Profits';
    $language_en['Global Dividend'] = 'Global Dividend';
    $language_en['Available Fund'] = 'Available Fund';
    $language_en['The growth of structure'] = 'The Growth of Network';
    $language_en['Your Referral Link'] = 'Your Referral Link';
    $language_en['Link for redirect to the Trust Wallet Dapp Browser'] = 'Link for redirect to the Trust Wallet Dapp Browser';
    $language_en['Your Downline Partners'] = 'Your Downline Partners';
    $language_en['Commission Received'] = 'Commission Received';
    $language_en['LEVEL'] = 'LEVEL';
    $language_en['Inactive'] = 'Inactive';
    $language_en['Active'] = 'Active';
    $language_en['Purchases'] = 'Purchases';
    $language_en['Buy'] = 'BUY';
    $language_en['Days'] = 'Days';
    $language_en['Contract Address'] = 'Contract Address';
    $language_en['Address'] = 'Address';
    $language_en['project month'] = 'PROJECT MONTH';
    $language_en['total participants'] = 'TOTAL PARTICIPANTS';
    $language_en['total transactions'] = 'total transactions';
    $language_en['total'] = 'total';
    $language_en['equivalent to'] = 'equivalent to';
    $language_en['USER ID'] = 'USER ID';
    $language_en['Auto Pool'] = 'Auto Pool';
    $language_en['Promotions'] = 'Promotions';
    $language_en['Wallet Address'] = 'Wallet Address';
    $language_en['Date Joined'] = 'Date Joined';
    $language_en['Date'] = 'Date';
    $language_en['From whom'] = 'From whom';
    $language_en['Received'] = 'Received';
    $language_en['Presentation'] = 'Presentation';
    $language_en['Articles'] = 'Articles';
    $language_en['Banner'] = 'Banner';
    $language_en['Video'] = 'Video';
    $language_en['Amount'] = 'Amount';
    $language_en['Line'] = 'Line';
    $language_en['Copy'] = 'Copy';


//login
	$language_en['by'] = 'by';
	$language_en['All RIGHT RESERVED'] = 'All RIGHT RESERVED';
	$language_en['Chat in Telegram'] = 'Chat in Telegram';
	$language_en['Any question you can get in our chat:'] = 'Any question you can get in our chat:';
	$language_en['Follow us on social networks'] = 'Follow us on social networks';
	$language_en['Login Manually'] = 'Login Manually';
	$language_en['Login']='Login';
	$language_en['smart-contract:']='smart-contract:';
	$language_en['Enter User ID or Ether Address'] = 'Enter User ID or Ether Address';
	$language_en['Or you can enter manually, Your ether address or User ID'] = 'Or you can enter manually, Your ether address or User ID';
	$language_en['Login Automatically'] = 'Login Automatically';
	$language_en['Automatic login if you have one of the following wallets:'] = 'Automatic login if you have one of the following wallets:';
	
?>